function CaLCFig(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 09-Jan-2017 16:21:39

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',24);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Concentration [\muM]','FontSize',26.4);

% Create xlabel
xlabel('Time [s]','FontSize',26.4);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','x');
set(plot1(2),'DisplayName','y');
set(plot1(3),'DisplayName','z');
set(plot1(4),'DisplayName','w');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.687292045353182 0.678535643434737 0.182431787476504 0.213603818615752],...
    'FontSize',21.6);

